config/routes.rb
BabyCasts::Application.routes.draw do
  root to: 'videos#index'

  devise_for :users, :controllers => { omniauth_callbacks: 'babycasts_omniauth_callbacks' }

  resources :videos, only: [:index, :show, :create] do
    collection do
      post 'results'
    end
  end

  get '/about' => 'pages#about'
end

app/models/settings.rb
class Settings < Settingslogic
  namespace Rails.env
  source "#{Rails.root}/config/application.yml"
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :provider, :facebook_uid, :facebook_token, :first_name, :last_name

  has_many :votes
  has_many :videos

  def self.find_for_facebook(auth)
    where(provider: auth.provider).where(facebook_uid: auth.uid).first || User.new
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  YOUTUBE_REGEX = /(?:https?:\/\/)?(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=)?([-_a-zA-Z0-9]{10,})\S*/

  attr_accessible :title, :description, :youtube_url, :sponsored, :youtube_id, :user

  validates :youtube_url, presence: true
  validates :title, length: { in: 3..40 }
  validates :description, length: { in: 3..140 }

  validate :check_youtube_url

  after_validation :parse_youtube_url

  has_many :votes

  belongs_to :user

  scope :available, where(sponsored: false).order('created_at DESC')
  scope :sponsored, where(sponsored: true)

  private

  def check_youtube_url
    errors.add(:youtube_url, :invalid) unless self.youtube_url =~ YOUTUBE_REGEX
  end

  def parse_youtube_url
    update_attributes youtube_id: youtube_url.gsub(YOUTUBE_REGEX, '\1') if youtube_id.nil?
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :like, :user, :video

  belongs_to :user
  belongs_to :video
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  self.responder = Babycasts::Responder
  protect_from_forgery
end

app/controllers/babycasts_omniauth_callbacks_controller.rb
class BabycastsOmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook(auth_hash)
    @user_authentication = Babycasts::UserAuthentication.new(auth_hash, user: @user)

    if @user_authentication.save
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      Rails.logger.error "Facebook integration failed: #{@user.errors.full_messages.to_sentence}."
      redirect_to root_path
    end
  end

  def failure
    Rails.logger.info("Facebook integration failed. Reasons: #{params}")
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  respond_to :html, :js
  before_filter :assign_user, :assign_video, :assign_video_search
  before_filter :load_sponsored_video, only: [:index, :results]

  def index
    @pages = Video.available.page(params[:page]).per(4)
    @videos = VideoPresenter.collect(@pages)
  end

  def results
    @video_search = Babycasts::VideoSearch.new(params[:babycasts_video_search])
    @pages        = @video_search.results.page(params[:page]).per(4)
    @videos       = VideoPresenter.collect(@pages)
    render :index
  end

  def show
    @video = VideoPresenter.new(Video.find params[:id])
  end

  def create
    @video = Video.new(params[:video])
    @video.save
    respond_with(@video)
  end

  private

  def assign_user
    @user = UserPresenter.new(current_user)
  end

  def assign_video
    @video = Video.new
  end

  def assign_video_search
    @video_search = Babycasts::VideoSearch.new
  end

  def load_sponsored_video
    @sponsored_video = VideoPresenter.collect([Video.sponsored.sample])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hide_modal
    action_name != "create" ? "fade" : ""
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BabyCasts - the first time we never forget</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
  <meta property='og:title' content='BabyCasts - the first time we never forget' />
  <meta property='og:url' content='http://http://babycasts.r12.railsrumble.com/'/>
  <meta property='og:image' content='<%= request.url %>assets/baby_face.png' />
  <meta property="og:type" content="Website" />
  <meta property="og:description" content="BabyCasts is an application created to help parents all over the world to share and find the bests baby hints and solutions for the most unexpected problems. Cause there is always a first time to have a baby either." />
  <meta name="description" content="BabyCasts is an application created to help parents all over the world to share and find the bests baby hints and solutions for the most unexpected problems. Cause there is always a first time to have a baby either." />
  <meta name="keywords" content="baby, parents, bebes, pais, mães, dad, mom, fraldas, mamadeira, infância, crianças, tutoriais, howto, dicas, cuidados, doenças, problemas, choro, cry, hints, babies, children, sons, daughter, help, sick"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
    </div>
  </div>
  <div class="container">
    <div class="menu-top">
      <ul>
        <%= @user.display_information %>
      </ul>
    </div>
    <div class="notice fade">
      <div class="alert alert-success"><%= notice %></div>
    </div>
    <div class="logo span7">
      <%= link_to(image_tag("logo.png"), root_path, :class => "pull-right") %>
    </div>
    <div class="row">
      <div class="span10 videos-list">
        <%= render "videos/search" %>
        <%= yield %>
      </div>
    </div>
  </div>
  <footer class="footer">
    <div class="container">
      <div>
        <p class="span5">Copyright &copy; <%= Date.today.year %> <%= link_to 'Gangnam Style team', about_path %>. <%= link_to("#RailsRumble2012", 'https://twitter.com/search?q=railsrumble2012&src=typd', target: '_blank') %></p>
          <%= link_to(image_tag('http://s0.railsrumble.com/assets/rr-logo-small-f2c869882ac5306656d15ac149cdd8a8.png'), 'http://railsrumble.com/', :target => "_blank") %>
      </div>
    </div>
  </footer>
  <script src="http://s0.railsrumble.com/banner.js" type="text/javascript"></script>
</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BabyCasts - the first time we never forget</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
  <meta property='og:title' content='BabyCasts - the first time we never forget' />
  <meta property='og:url' content='http://http://babycasts.r12.railsrumble.com/'/>
  <meta property='og:image' content='<%= request.url %>assets/baby_face.png' />
  <meta property="og:type" content="Website" />
  <meta property="og:description" content="BabyCasts is an application created to help parents all over the world to share and find the bests baby hints and solutions for the most unexpected problems. Cause there is always a first time to have a baby either." />
  <meta name="description" content="BabyCasts is an application created to help parents all over the world to share and find the bests baby hints and solutions for the most unexpected problems. Cause there is always a first time to have a baby either." />
  <meta name="keywords" content="baby, parents, bebes, pais, mães, dad, mom, fraldas, mamadeira, infância, crianças, tutoriais, howto, dicas, cuidados, doenças, problemas, choro, cry, hints, babies, children, sons, daughter, help, sick"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
    </div>
  </div>
  <div class="container">
    <div class="notice fade">
      <div class="alert alert-success"><%= notice %></div>
    </div>
    <div class="logo span7">
      <%= link_to(image_tag("logo.png"), root_path, :class => "pull-right") %>
    </div>
    <div class="row">
      <div class="span10 videos-list">
        <%= yield %>
      </div>
    </div>
  </div>
  <footer class="footer">
    <div class="container">
      <div>
        <p class="span5">Copyright &copy; <%= Date.today.year %> Gangnam Style team. <%= link_to("#RailsRumble2012", 'https://twitter.com/search?q=railsrumble2012&src=typd', target: '_blank') %></p>
          <%= link_to(image_tag('http://s0.railsrumble.com/assets/rr-logo-small-f2c869882ac5306656d15ac149cdd8a8.png'), 'http://railsrumble.com/', :target => "_blank") %>
      </div>
    </div>
  </footer>
  <script src="http://s0.railsrumble.com/banner.js" type="text/javascript"></script>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<h3>Gangnam Style team</h3>

<p>Project by <a href='http://github.com/lucascaton'>Lucas Caton</a>, <a href='http://github.com/flaviomuniz'>Flavio Muniz</a>, <a href='http://github.com/tomas-stefano'>Tomas D'Stefano</a> and <a href='http://github.com/joaomdmoura'>Joao Moura</a> (<a href='http://railsrumble.com/'>Rails Rumble 2012</a>).</p>

app/views/users/_info.html.erb
<li class="user-logged">
  <%= user.facebook_avatar %>
  <strong><%= user.full_name %></strong>
  <%= user.logout_link %>
</li>

app/views/users/_sign_in_links.html.erb
<li><%= link_to 'Sign in with facebook', sign_in_via_facebook_path %></li>

app/views/videos/_new.html.erb
<%= simple_form_for(@video, url: videos_path, remote: true) do |f| %>
<div class="modal <%= hide_modal %>" id="newVideo">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Create a new video</h3>
  </div>

  <div class="modal-body">
    <%= f.input :youtube_url, input_html: { class: "span5" } %>
    <%= f.input :title, input_html: { class: "span videoTitle"} %>
    <%= f.input :description, input_html: { class: "span5 videoDescription", rows: "2" } %>

    </ul>
  </div>
  <div class="modal-footer">
    <%= button_tag "Close", type: "button", class: "btn", :'data-dismiss' => "modal", :"aria-hidden" => "true" %>
    <%= f.submit "Save video", class: "btn btn-primary btn-large" %>
  </div>
</div>
<% end %>

app/views/videos/_search.html.erb
<div class="input-append">
  <%= simple_form_for(@video_search, url: results_videos_path, wrapper: :default) do |f| %>
    <%= f.input :expected_search, autofocus: true, label: false, placeholder: "Search", input_html: {id: "appendedInputButton", class: "span8", size: "16", type: "search"} %>

    <%= button_tag(
        type: 'submit',
        class: 'btn') do %>
      Search
    <% end %>

    <%= button_tag(
        type: 'button',
        class: @user.upload_button_class,
        :'data-toggle' => "modal",
        :'data-target' => "#newVideo",
        rel: "tooltip",
        :'data-placement' => "top",
        :'data-original-title' => "You must be logged in order to upload.") do %>
      Upload
    <% end %>
  <% end %>
</div>

app/views/videos/_share_on_social_media.html.erb
<div class="popover top <%= video.youtube_id %>">
  <div class="arrow"></div>
  <h3 class="popover-title">Share</h3>
  <div class="popover-content">
    <p>

    </p>
    <div class="popover-footer"></div>
  </div>
</div>
<%= link_to("Share", '', :class => "btn btn-system-default popover-click")%>

app/views/videos/_video.html.erb
<div class="<%= video.presentation %>" data-video_id="<%= video.youtube_id %>_<%= video.id %>">
  <%= image_tag("http://cdn1.iconfinder.com/data/icons/socialmediaicons_v120/48/youtube.png", :class => "link-to-play alternative-to-play") %>
  <%= image_tag("http://img.youtube.com/vi/#{video.youtube_id}/0.jpg", :class => "image-preview") %>

  <div class="span6">
    <%= link_to('javascript:;', :class => "close-video btn btn-mini btn-danger") do %>
      <i class='icon-remove'></i> Close
    <% end %>

    <h2><%= video.title %></h2>
    <p>
      <%= video.description %>
    </p>
      <div class="share">
        <strong>Share</strong><br />
        <%= link_to(image_tag('http://cdn1.iconfinder.com/data/icons/WPZOOM_Social_Networking_Icon_Set/24/facebook.png'), "http://www.facebook.com/sharer.php?u=#{request.url}videos/#{video.id}&t=#{video.title}")%>
        <%= link_to(image_tag('http://cdn1.iconfinder.com/data/icons/WPZOOM_Social_Networking_Icon_Set/24/twitter.png'), "http://twitter.com/share?url=#{request.url}videos/#{video.id}&text=#{video.title}")%>
        <%= link_to(image_tag('http://cdn1.iconfinder.com/data/icons/WPZOOM_Social_Networking_Icon_Set/24/google.png'), "http://plus.google.com/share?url=#{request.url}videos/#{video.id}")%>
      </div>
    <%= video.sponsored_mark %>
  </div>
  <div class="video-frame span8" id="<%= video.youtube_id %>_<%= video.id %>"></div>
</div>

app/views/videos/create.js.erb
<% if @video.persisted? %>
  $(".notice .alert-success").html("<%= notice.html_safe %>");
  $("#newVideo").modal('hide');
<% else %>
  $("#newVideo").html("<%= escape_javascript(render 'videos/new') %>")
<% end %>

app/views/videos/index.html.erb
<%= render @sponsored_video %>
<%= render @videos %>

<% if user_signed_in? %>
  <%= render "videos/new" %>
<% end %>

<div class="pagination">
	<%= paginate @pages, :window => 2 %>
</div>

app/views/videos/show.html.erb
<%= render @video %>